<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/math.proto

namespace GPBMetadata\Proto;

class Math
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abc020a1070726f746f2f6d6174682e70726f746f12096563636f2e6d61" .
            "746822220a0a4164645265717565737412090a017818012001280512090a" .
            "017918022001280522170a084164645265706c79120b0a0373756d180120" .
            "01280522280a105375627374726163745265717565737412090a01781801" .
            "2001280512090a0179180220012805221e0a0e5375627374726163745265" .
            "706c79120c0a04646966661801200128053288010a0a43616c63756c6174" .
            "6f7212330a0361646412152e6563636f2e6d6174682e4164645265717565" .
            "73741a132e6563636f2e6d6174682e4164645265706c79220012450a0973" .
            "7562737472616374121b2e6563636f2e6d6174682e537562737472616374" .
            "526571756573741a192e6563636f2e6d6174682e53756273747261637452" .
            "65706c7922004203d00201620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

