<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/math.proto

namespace Ecco\Math;

/**
 * Protobuf type <code>ecco.math.Calculator</code>
 */
interface CalculatorInterface
{
    /**
     * Method <code>add</code>
     *
     * @param \Ecco\Math\AddRequest $request
     * @return \Ecco\Math\AddReply
     */
    public function add(\Ecco\Math\AddRequest $request);

    /**
     * Method <code>substract</code>
     *
     * @param \Ecco\Math\SubstractRequest $request
     * @return \Ecco\Math\SubstractReply
     */
    public function substract(\Ecco\Math\SubstractRequest $request);

}

